### ISSUE TITLE
SyntaxError: Unexpected token =

### ISSUE THREAD

**Issue by bendulum** [Novaleaf/phantomjscloud-node-examples#4]
I'm trying out your service to render .png screenshots of websites using Node.
Using Windows7 to test locally.
Here is my code (the relevant parts):

```
var c = function() { ... }; // callback
var file = { ... }; // job information
var apiKey = undefined;
var browser = new phantomJsCloud.BrowserApi(apiKey);

browser.requestSingle({
    url: file.url,
    renderType: 'png'
}, function(e, res) {
    if (e) return c(e, false);
    if (res.statusCode != 200) return c('Response error.', false);
    fs.writeFile(
        file.name,
        res.content.data,
        {
            encoding: res.content.encoding
        },
        function(e) {
            e ? c(e, false) : c(null, file);
        }
    );
});
```
Getting the following error:

```
SyntaxError: Unexpected token =
    at exports.runInThisContext (vm.js:53:16)
    at Module._compile (module.js:404:25)
    at Object.Module._extensions..js (module.js:432:10)
    at Module.load (module.js:356:32)
    at Function.Module._load (module.js:313:12)
    at Module.require (module.js:366:17)
    at require (module.js:385:17)
    at Object.<anonymous> (X:\...\node_modules\xlib\src\internal\mockmocha.ts:3:1)
    at Module._compile (module.js:425:26)
    at Object.Module._extensions..js (module.js:432:10)
    at Module.load (module.js:356:32)
    at Function.Module._load (module.js:313:12)
    at Module.require (module.js:366:17)
    at require (module.js:385:17)
    at Object.<anonymous> (X:\...\node_modules\xlib\src\_index.ts:52:1)
    at Module._compile (module.js:425:26)
    at Object.Module._extensions..js (module.js:432:10)
    at Module.load (module.js:356:32)
    at Function.Module._load (module.js:313:12)
    at Module.require (module.js:366:17)
    at require (module.js:385:17)
    at Object.<anonymous> (X:\...\node_modules\phantomjscloud\src\refs.ts:14:1)
```

Any pointers? Thank you!

**Edit** 
Just realized this might be the wrong repository for this issue. 
Should I repost to `phantomjscloud-node`?

**Comment by jasonswearingen** [comment]
hi, sorry I didn't see this until now, I will update the repo in the next day.

**edit**:   will be doing this this coming weekend (aprox may 6)

**Comment by jasonswearingen** [comment]
hi i think this is due to you running an old version of node.   can you please get the latest release of phantomjscloud and try again?  the latest version works down to node 4.x  (previously only worked on 6.x)

**Comment by jasonswearingen** [comment]
otherwise please give me a full example code, because it works in my environments! (windows and ubuntu)
