### ISSUE TITLE
TypeError: phantomJsCloud.setDebug is not a function

### ISSUE THREAD

**Issue by janilahti** [Novaleaf/phantomjscloud-node-examples#6]
Installation 1. thru 3. is done, then
`node ./dist/advanced/query-and-mine-alexa-topsites.js`
gives
```
logLevel=DEBUG
envLevel=PREPROD
isDev=TRUE
2017-05-01T09:39:42.336Z promise.logPromiseUnhandledRejections DEBUG exec xlib.diagnostics.logger.logPromiseUnhandledRejections()

[...]\phantomjscloud-examples\src\advanced\query-and-mine-alexa-topsites.ts:19
        phantomJsCloud.setDebug(true);
                ^
TypeError: phantomJsCloud.setDebug is not a function
    at runExample ([...]\phantomjscloud-examples\src\advanced\query-and-mine-alexa-topsites.ts:19:17)
    at Object.<anonymous> ([...]\phantomjscloud-examples\src\advanced\query-and-mine-alexa-topsites.ts:176:5)
[...]
```
When setDebug line is commented out the example runs but zero urls are extracted.
```
[...]
2017-05-01T09:41:22.736Z phantomjscloud\dist\_index.js DEBUG _task_worker FINISH
2017-05-01T09:41:22.739Z dist\advanced\query-and-mine-alexa-topsites.js INFO finished reading page http://www.alexa.com/topsites/global
2017-05-01T09:41:22.744Z dist\advanced\query-and-mine-alexa-topsites.js INFO got url amount = 0
2017-05-01T09:41:22.748Z dist\advanced\query-and-mine-alexa-topsites.js INFO []
2017-05-01T09:41:22.756Z dist\advanced\query-and-mine-alexa-topsites.js INFO DONE!  alexiaTop500GatherTime = 14.308sec $0.0006063620147953431 writePlainTextTime=0.006999999999999673sec $0
```
Additionally, there are some references to 'Alexia' in place of 'Alexa'.

**Comment by jasonswearingen** [comment]
hi, sorry the alexa example doesn't work anymore due to changes to the alexa website (now more restrictive)   however you are right regarding the ```setDebug``` issue (out dated ```node-phantomjscloud``` module)

I will update both today or tomorrow, probably replacing alexa with another example.

**edit**:   will be doing this this coming weekend (aprox may 6)

**Comment by jasonswearingen** [comment]
hi, you can't use the alexa example anymore unfortunately, they put the top 100 list behind a paywall.  so will comment out the example.
